select 
	TZ_AREA_ID 
from 
	PS_TZ_SITEI_AREA_T PT1,
	PS_TZ_SITEI_ATYP_T PT2 
where 
	PT1.TZ_SITEI_ID=PT2.TZ_SITEI_ID 
	and PT1.TZ_AREA_TYPE_ID=PT2.TZ_AREA_TYPE_ID 
	and PT1.TZ_SITEI_ID=? 
	and PT2.TZ_AREA_TYPE=?
	and TZ_AREA_TYPE_STATE = 'Y'