select 
	PT1.TZ_TEMP_PCCODE,
	PT1.TZ_PCTEMP_SCRIPT_HTML
from 
	PS_TZ_SITEI_TEMP_T PT1, 
	PS_TZ_SITEI_COLU_T PT2, 
	PS_TZ_SITEI_MENU_T PT3 
where
	PT1.TZ_SITEI_ID = PT2.TZ_SITEI_ID 
	and PT2.TZ_SITEI_ID = PT3.TZ_SITEI_ID 
	and PT1.TZ_TEMP_ID = PT2.TZ_TEMP_ID  
	and PT2.TZ_COLU_ID = PT3.TZ_MENU_COLUMN 
	and PT1.TZ_TEMP_STATE = 'Y' 
	and PT1.TZ_SITEI_ID = ? 
	and PT3.TZ_MENU_ID = ?