select 
	PT.TZ_MENU_NAME, 
	PT.TZ_MENU_TYPE_ID, 
	PT.TZ_MENU_COLUMN,
	PT.TZ_TYPE_IMG, 
	PT.TZ_NOW_IMG, 
	MT.TZ_TYPE_DESCR,
	MT.TZ_IS_ADD,
	MT.TZ_ADD_COLU,
	PT.TZ_IS_DEL,
	PT.TZ_IS_EDITOR,
	PT.TZ_MENU_URL,
	PT.TZ_MENU_OPURL_TYPE 
from 
	PS_TZ_SITEI_MENU_T PT, 
	PS_TZ_SITEI_MTYP_T MT 
where 
	MT.TZ_SITEI_ID = PT.TZ_SITEI_ID 
	and MT.TZ_MENU_TYPE_ID = PT.TZ_MENU_TYPE_ID 
	and PT.TZ_SITEI_ID=? 
	and PT.TZ_MENU_ID=? 
	and MT.TZ_TYPE_STATE='Y'