Ext.define('KitchenSink.view.bulkEmailAndSMS.znx.znxAttaModel',{
    extend:'Ext.data.Model',
    fields:[
        {name:'znxQfId'},
        {name:'attaID'},
        {name:'attaName'},
        {name:'attaUrl'}
    ]
});