SELECT TMP.TZ_APP_INS_ID,
	   TMP.TZ_SCORE_INS_ID,
	   TMP.TZ_SCORE_MODAL_ID,
	   TMP.TREE_NAME,
	   TMP.TREE_NODE,
	   TMP.TZ_SCORE_NUM,
	   CASE
	   	WHEN @rowtotal = TMP.TZ_SCORE_NUM 
	   	THEN @rownum
		WHEN @rowtotal := TMP.TZ_SCORE_NUM 
		THEN @rownum :=@rownum + 1
		WHEN @rowtotal = 0 
		THEN @rownum :=@rownum + 1
	   END AS RANK
FROM
(SELECT A.TZ_APP_INS_ID,
		A.TZ_SCORE_INS_ID,
		B.TZ_SCORE_MODAL_ID,
		C.TREE_NAME,
		D.TREE_NODE,
		E.TZ_SCORE_NUM 
	FROM PSTREENODE D,
		 PS_TZ_CP_PW_KS_TBL A ,
		 PS_TZ_SRMBAINS_TBL B,
		 PS_TZ_RS_MODAL_TBL C,
		 PS_TZ_CJX_TBL E
	WHERE A.TZ_SCORE_INS_ID = B.TZ_SCORE_INS_ID 
	AND B.TZ_SCORE_MODAL_ID=C.TZ_SCORE_MODAL_ID 
	AND D.TREE_NAME=C.TREE_NAME 
	AND D.PARENT_NODE_NUM=0 
	AND E.TZ_SCORE_INS_ID=A.TZ_SCORE_INS_ID 
	AND E.TZ_SCORE_ITEM_ID=D.TREE_NODE
	AND C.TZ_JG_ID=? 
	AND A.TZ_CLASS_ID=? 
	AND A.TZ_APPLY_PC_ID=? 
	AND A.TZ_PWEI_OPRID=?
	ORDER BY E.TZ_SCORE_NUM DESC
) TMP,
(SELECT @rownum := 0 ,@rowtotal := NULL) RANK