SELECT A.TZ_CLASS_NAME,
       YEAR(A.TZ_START_DT) TZ_START_YEAR,
       A.TZ_JG_ID,
       A.TZ_PS_APP_MODAL_ID,
       A.TZ_ZLPS_SCOR_MD_ID,
       A.TZ_APP_MODAL_ID,
       C.TZ_APP_FORM_STA,
       B.OPRID,
       D.TZ_REALNAME,
       B.TZ_MSH_ID,
       F.TZ_BATCH_NAME,
       (SELECT G.TREE_NAME 
        FROM PS_TZ_RS_MODAL_TBL G 
        WHERE G.TZ_JG_ID=A.TZ_JG_ID AND G.TZ_SCORE_MODAL_ID=A.TZ_ZLPS_SCOR_MD_ID
       ) TREE_NAME,
       G.TZ_PRJ_NAME
FROM PS_TZ_AQ_YHXX_TBL D,
	 PS_TZ_APP_INS_T C,
	 PS_TZ_FORM_WRK_T B,
	 PS_TZ_CLS_BATCH_T F,
	 PS_TZ_CLASS_INF_T A,
	 PS_TZ_PRJ_INF_T G
WHERE A.TZ_CLASS_ID=B.TZ_CLASS_ID 
	 AND B.TZ_APP_INS_ID = C.TZ_APP_INS_ID 
	 AND B.OPRID=D.OPRID  
	 AND A.TZ_PRJ_ID = G.TZ_PRJ_ID 
	 AND A.TZ_CLASS_ID=? 
	 AND A.TZ_CLASS_ID = F.TZ_CLASS_ID 
	 AND F.TZ_BATCH_ID=? 
	 AND B.TZ_APP_INS_ID=?