Ext.define('KitchenSink.view.template.survey.question.wjdcModel', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'TZ_DC_WJ_ID'},
        {name: 'TZ_APP_TPL_ID'},
        {name: 'TZ_JG_ID'},
        {name:'TZ_DC_WJBT'},
        {name: 'TZ_APP_TPL_LX'},
        {name:'TZ_APP_TPL_LAN'},
        {name:'TZ_DC_JTNR'},
        {name:'TZ_DC_JWNR'},
        {name: 'TZ_DC_WJ_ZT'},
        {name: 'TZ_DC_WJ_FB'},
        {name: 'TZ_DC_WJ_KSRQ'},
        {name:'TZ_DC_WJ_KSSJ'},
        {name: 'TZ_DC_WJ_JSRQ'},
        {name:'TZ_DC_WJ_JSSJ'},
        {name:'TZ_DC_WJ_PC_URL'},
        {name:'TZ_DC_WJ_MB_URL'},
        {name:'TZ_DC_WJ_URL'},
        {name:'TZ_DC_WJ_DLZT'},
        {name:'TZ_DC_WJ_DTGZ'},
        {name:'TZ_DC_WJ_IPGZ'},
        {name:'TZ_DC_WJ_JSGZ'},
        {name:'TZ_DC_WJ_NM'},
        {name:'TZ_DC_WJ_PWD'},
        {name:'TZ_DC_WJ_NEEDPWD'},
        {name:'TZ_DC_WJ_QYQD'},
        {name:'TZ_DC_WJ_QDNR'},
        {name:'TZ_DC_WJ_JGNR'},
        {name:'TZ_DC_WJ_SFTZ'},
        {name:'TZ_DC_WJ_TZDZ'},
        {name:'TZ_DC_WJ_TLSJ'}
    ]
});
