/**
 * 自动标签
 * 标签前一年递补保留：前一年递补保留名单是否存在于“当前批次下所有报名表状态等于提交且初审状态不等于审批拒绝的考生中”
 * TZ_APP_FORM_STA：S 保存；  U 提交；  P 预提交
 * TZ_FORM_SP_STA：A 审批通过； B 拒绝； N 待审核
 */

SELECT X.TZ_APP_INS_ID
FROM PS_TZ_FORM_WRK_T Y,
     PS_TZ_APP_INS_T X
WHERE Y.TZ_APP_INS_ID=X.TZ_APP_INS_ID
  AND X.TZ_APP_FORM_STA='U'
  AND Y.TZ_FORM_SP_STA<>'B'
  AND Y.TZ_BATCH_ID=?
  AND Y.TZ_CLASS_ID=?
  AND EXISTS (SELECT 'Y'  
  	FROM PS_TZ_APP_INS_T A,
		PS_TZ_QYNDBBL_KS_T B,
		PS_TZ_AQ_YHXX_TBL C
	WHERE A.TZ_APP_INS_ID=X.TZ_APP_INS_ID 
		AND B.TZ_PRJ_ID=(
			SELECT TZ_PRJ_ID 
			FROM PS_TZ_CLASS_INF_T 
			WHERE TZ_CLASS_ID=Y.TZ_CLASS_ID)
		AND B.TZ_KSSSYEAR =YEAR(sysdate())-1
		AND B.TZ_MSH_ID=C.TZ_MSH_ID 
		AND C.OPRID=A.ROW_ADDED_OPRID)