DELETE FROM PS_TZ_CS_KS_TBL 
WHERE
    TZ_CLASS_ID = ?
    AND TZ_APPLY_PC_ID = ?
    AND NOT EXISTS( SELECT 
        'x'
    FROM
        PS_TZ_FORM_WRK_T A,
        PS_TZ_APP_INS_T B
    
    WHERE
        (A.TZ_FORM_SP_STA <> 'B'
        OR ISNULL(A.TZ_FORM_SP_STA))
        AND A.TZ_APP_INS_ID = B.TZ_APP_INS_ID
        AND B.TZ_APP_FORM_STA = 'U'
        AND A.TZ_CLASS_ID = PS_TZ_CS_KS_TBL.TZ_CLASS_ID
        AND A.TZ_BATCH_ID = PS_TZ_CS_KS_TBL.TZ_APPLY_PC_ID
        AND A.TZ_APP_INS_ID = PS_TZ_CS_KS_TBL.TZ_APP_INS_ID)