SELECT
	B.TZ_SCHEDULE_ID,
	B.TZ_COURSE_ID,
	date_format(
		B.TZ_CLASS_START_TIME,
		'%Y-%m-%d %H:%i:%S'
	) AS TZ_CLASS_START_TIME,
	date_format(
		B.TZ_CLASS_END_TIME,
		'%Y-%m-%d %H:%i:%S'
	) AS TZ_CLASS_END_TIME,
	D.TZ_COURSE_TYPE_NAME,
	E.TZ_COURSE_NAME,
	B.TZ_SCHEDULE_TYPE,
	B.TZ_ROOM_ID,
	B.TZ_ROOM_KEY
FROM
	PX_TEA_SCHEDULE_T B
LEFT JOIN PX_COURSE_TYPE_T D ON B.TZ_COURSE_TYPE_ID = D.TZ_COURSE_TYPE_ID
LEFT JOIN PX_COURSE_T E ON B.TZ_COURSE_ID = E.TZ_COURSE_ID
WHERE
	B.OPRID =?
AND B.TZ_CLASS_START_TIME <=?
AND B.TZ_CLASS_START_TIME >=?
ORDER BY
	B.TZ_CLASS_START_TIME ASC
limit ?,?