SELECT
	(
		SELECT
			B.TZ_ZHZ_DMS
		FROM
			PS_TZ_PT_ZHZXX_TBL B
		WHERE
			B.TZ_ZHZJH_ID = 'PX_CHANGE_TYPE' 
		AND CONVERT(B.TZ_ZHZ_ID,SIGNED)  = A.TZ_CHANGE_TYPE
	) AS TZ_CHANGE_TYPE,
	A.TZ_BEFORE_CHANGE,
	A.TZ_AFTER_CHANGE,
	A.TZ_CHANGE,
	date_format(
		A.TZ_CHANGE_TIME,
		'%Y-%m-%d %H:%i:%S'
	) AS TZ_CHANGE_TIME
FROM
	PK_TES_INTEGRAL_CHANGE_T A
WHERE
	A.OPRID = ?
ORDER BY
	A.TZ_CHANGE_TIME DESC;