SELECT
	date_format(
		B.TZ_CLASS_START_TIME,
		'%Y-%m-%d'
	) AS TZ_CLASS_START_TIME,
	hour(
		B.TZ_CLASS_START_TIME) AS TZ_HOUR
FROM
	PX_TEA_SCHEDULE_T B
WHERE
	B.OPRID =?
AND B.TZ_CLASS_START_TIME <=?
AND B.TZ_CLASS_START_TIME >=?