SELECT A.TZ_XXX_BH 
 , A.TZ_XXX_MC 
 , A.TZ_COM_LMC 
 , A.TZ_PAGE_NO 
 , A.TZ_XXX_RQGS 
 , A.TZ_XXX_NFMIN 
 , A.TZ_XXX_NFMAX 
 , A.TZ_XXX_ZSXZGS 
 , A.TZ_XXX_ZDXZGS 
 , A.TZ_XXX_YXSCLX 
 , A.TZ_XXX_YXSCDX 
 , A.TZ_XXX_BT_BZ 
 , A.TZ_XXX_CHAR_BZ 
 , A.TZ_XXX_MINLEN 
 , A.TZ_XXX_MAXLEN 
 , A.TZ_XXX_NUM_BZ 
 , A.TZ_XXX_MIN 
 , A.TZ_XXX_MAX 
 , A.TZ_XXX_XSWS 
 , A.TZ_XXX_GDGSJY 
 , A.TZ_XXX_DRQ_BZ 
 , A.TZ_XXX_MIN_LINE 
 , A.TZ_XXX_MAX_LINE 
 , A.TZ_TJX_SUB 
 , E.TZ_APPCLS_PATH 
 , E.TZ_APPCLS_NAME 
 , E.TZ_APPCLS_METHOD 
 , C.TZ_JYGZ_TSXX 
  FROM PS_TZ_APP_XXXPZ_T A 
  ,PS_TZ_APPXX_JYGZ_T C 
  ,PS_TZ_JYGZ_DY_T D 
  ,PS_TZ_APPCLS_TBL E 
 WHERE A.TZ_APP_TPL_ID = ? 
   AND A.TZ_APP_TPL_ID = C.TZ_APP_TPL_ID 
   AND A.TZ_XXX_BH = C.TZ_XXX_BH 
   AND C.TZ_QY_BZ = 'Y' 
   AND C.TZ_JYGZ_ID = D.TZ_JYGZ_ID 
   AND D.TZ_JYGZ_APPCLSID = E.TZ_APPCLS_ID 
  ORDER BY A.TZ_XXX_SLID