SELECT DISTINCT A.TZ_XXX_BH 
  FROM PS_TZ_APP_DHCC_VW A 
 WHERE TZ_APP_INS_ID = ? 
   AND TZ_APP_TPL_ID = ? 
   AND TZ_XXX_NO = ? 
   AND NOT EXISTS( 
 SELECT 'Y' 
  FROM PS_TZ_APP_DHCC_VW B 
 WHERE A.TZ_XXX_BH = B.TZ_XXX_BH 
   AND A.TZ_APP_INS_ID =B.TZ_APP_INS_ID 
   AND A.TZ_APP_TPL_ID =B.TZ_APP_TPL_ID 
   AND A.TZ_D_XXX_BH = B.TZ_D_XXX_BH 
   AND B.TZ_IS_CHECKED = 'Y')