 SELECT TZ_XXX_BH 
     FROM PS_TZ_FORM_ATT_VW3 
     WHERE TZ_APP_INS_ID = ?
   		AND TZ_D_XXX_BH = ?
   		AND TZ_XXX_BH LIKE ?
   		AND TZ_XXX_NO = ?
   		AND TZ_COM_LMC = ?
	    ORDER BY TZ_APP_INS_ID,TZ_APP_TPL_ID,TZ_D_XXX_BH,TZ_XXX_BH
   		LIMIT ?,1