SELECT TZ_APP_S_TEXT 
 ,TZ_COM_LMC 
 FROM
  PS_TZ_APP_CC_VW2
     WHERE TZ_APP_INS_ID = ?
   		AND TZ_D_XXX_BH = ?
   		AND TZ_XXX_BH LIKE ?
   		AND TZ_XXX_NO = ?
   		ORDER BY TZ_APP_INS_ID,TZ_APP_TPL_ID,TZ_D_XXX_BH,TZ_XXX_BH
		LIMIT ?,1