 SELECT TZ_IS_CHECKED 
     FROM PS_TZ_APP_DHCC_VW2 A
     WHERE TZ_APP_INS_ID = ?
   AND TZ_D_XXX_BH = ?
   AND TZ_XXX_BH LIKE ?
   AND TZ_XXX_NO = ?
   AND TZ_XXXKXZ_MC = ?
   ORDER BY TZ_APP_INS_ID,TZ_APP_TPL_ID,TZ_D_XXX_BH,TZ_XXX_BH
   LIMIT ?,1