SELECT 
	A.TZ_CLASS_NAME,
	B.OPRID,
	C.NATIONAL_ID,
    D.TZ_MSH_ID,
	C.TZ_REALNAME,
	DATE_FORMAT(C.BIRTHDATE,"%Y-%m-%d") BIRTHDATE,
	(year(now())-year(C.BIRTHDATE)) AGE,
	C.TZ_GENDER,
	(SELECT X.TZ_ZHZ_DMS FROM PS_TZ_PT_ZHZXX_TBL X WHERE X.TZ_ZHZ_ID=C.TZ_GENDER AND X.TZ_ZHZJH_ID='TZ_GENDER') TZ_GENDER_DESC,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_SCHOOL_NAME,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_ZGXL,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_GZ_SZD,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_COMPANY_NAME,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_DEPARTMENT,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_POSITION,
	(SELECT M.TZ_APP_S_TEXT FROM PS_TZ_APP_CC_T M WHERE M.TZ_APP_INS_ID=B.TZ_APP_INS_ID AND M.TZ_XXX_BH=?) TZ_ZZCY_NAME
FROM 
	PS_TZ_AQ_YHXX_TBL D,
	PS_TZ_REG_USER_T C,
	PS_TZ_FORM_WRK_T B,
	PS_TZ_CLASS_INF_T A
WHERE B.OPRID=D.OPRID
	AND B.OPRID=C.OPRID
	AND D.TZ_JG_ID=?
	AND B.TZ_APP_INS_ID=?
	AND A.TZ_CLASS_ID=?