SELECT 
	A.TZ_PWEI_OPRID,
	B.TZ_DLZH_ID,
	B.TZ_REALNAME,
	B.TZ_MOBILE,
	B.TZ_EMAIL,
	A.TZ_PWZBH,
	C.TZ_CLPS_GR_NAME,
	A.TZ_PYKS_XX,
	A.TZ_PWEI_ZHZT,
	(SELECT D.TZ_ZHZ_DMS
	 FROM PS_TZ_PT_ZHZXX_TBL D
	 WHERE D.TZ_ZHZ_ID=A.TZ_PWEI_ZHZT AND D.TZ_ZHZJH_ID='TZ_PWEI_ZHZT'
	) TZ_PWEI_ZHZT_DESC,
    E.OPERPSWD,
    F.TZ_CS_PASSWORD,
    F.TZ_YNYW,
    (SELECT D.TZ_ZHZ_DMS
	 FROM PS_TZ_PT_ZHZXX_TBL D
	 WHERE D.TZ_ZHZ_ID=F.TZ_YNYW AND D.TZ_ZHZJH_ID='TZ_YNYW'
	 ) TZ_YNYW_DESC 
FROM 
	PS_TZ_CLPS_PW_TBL A
	LEFT JOIN PS_TZ_AQ_YHXX_TBL B
	ON A.TZ_PWEI_OPRID=B.OPRID
	LEFT JOIN PS_TZ_CLPS_GR_TBL C
	ON A.TZ_PWZBH=C.TZ_CLPS_GR_ID
    LEFT JOIN PSOPRDEFN E
    ON A.TZ_PWEI_OPRID=E.OPRID
    LEFT JOIN PS_TZ_PW_EXT_T F
    ON F.OPRID=B.OPRID
WHERE 
	A.TZ_CLASS_ID=? 
	AND A.TZ_APPLY_PC_ID=? 
ORDER BY F.TZ_YNYW