SELECT 
	C.TZ_ZDBQ_ID TZ_BQ_ID,
	C.TZ_BIAOQZ_NAME TZ_BQ_NAME
FROM 
	PS_TZ_CS_KSBQ_T C
WHERE C.TZ_APP_INS_ID=?
UNION 
SELECT 
	A.TZ_LABEL_ID TZ_BQ_ID,
	B.TZ_LABEL_NAME TZ_BQ_NAME
FROM 
	PS_TZ_FORM_LABEL_T A,
	PS_TZ_LABEL_DFN_T B
WHERE 
	A.TZ_LABEL_ID=B.TZ_LABEL_ID
	AND A.TZ_APP_INS_ID=?