select 
	A.ROLENAME,
	A.DESCR,
	A.DESCRLONG,
	A.VERSION,
	A.ROLESTATUS,
	A.ROLE_PCODE_RULE_ON,
	A.ROLE_QUERY_RULE_ON,
	A.LDAP_RULE_ON,
	A.ALLOWNOTIFY,
	A.ALLOWLOOKUP,
	B.TZ_ROLE_TYPE 
from 
	PSROLEDEFN A,
	PS_TZ_JG_ROLE_T B 
where 
	A.ROLENAME = B.ROLENAME 
	and B.TZ_JG_ID = ? 
	and (
		B.TZ_ROLE_TYPE='A' 
		or B.TZ_ROLE_TYPE='B' 
		or B.TZ_ROLE_TYPE='C'
	)