select 
	a.TZ_ATTACHSYSFILENA,
	a.TZ_PRIORITY,
	b.TZ_ATT_A_URL,
	a.TZ_IMG_DESCR,
	a.TZ_IMG_TRS_URL,
	b.TZ_SL_ATTACHSYSNAM 
from 
	PS_TZ_ART_PIC_T a,
	PS_TZ_ART_TPJ_T b 
where 
	a.TZ_ART_ID=? 
	and a.TZ_ATTACHSYSFILENA=b.TZ_ATTACHSYSFILENA 
order by a.TZ_PRIORITY ASC