SELECT
	A.TZ_MENU_ID,
	A.TZ_MENU_NAME,
	C.TZ_MTYPE_IMG,
	A.TZ_MOBILE_NEWFLG
FROM
	PS_TZ_SITEI_MENU_T A,
	PS_TZ_SITEI_DEFN_T B,
	PS_TZ_SITEI_MNPF_T C
WHERE
	C.TZ_SITEI_ID = A.TZ_SITEI_ID
AND B.TZ_SITEI_ID = A.TZ_SITEI_ID
AND C.TZ_MENU_ID = A.TZ_MENU_ID
AND C.TZ_SKIN_ID = B.TZ_SKIN_ID
AND A.TZ_SITEI_ID = ?
AND A.TZ_SHOW_MOBILE_FLG <> 'N'
ORDER BY
	A.TZ_SHOWM_ORDER ASC
	limit 3,?